name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup with node and yarn
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Enable Corepack and setup Yarn
        run: |
          corepack enable
          cd web
          corepack prepare yarn@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate
          yarn --version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.24"

      - name: Build web
        run: cd web && yarn install && yarn build

      - name: Build plugin
        run: cd hermes-plugin && npm install && npm run build

      - name: Build Go binary
        run: make bin/linux

      - name: Run Go test
        run: make go/test

      - name: Run web test (continue on failure)
        run: cd web && yarn test:ember --timeout 600000 || true
        continue-on-error: true
